config/routes.rb
Rails.application.routes.draw do
  resources :politicas
  resources :internacionals
  resources :nacionals
  resources :farandulas
  resources :deportes
  resources :noticia
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "noticia#index"


end

app/models/deporte.rb
class Deporte < ApplicationRecord
end

app/controllers/deportes_controller.rb
class DeportesController < ApplicationController
  before_action :set_deporte, only: %i[ show edit update destroy ]

  # GET /deportes or /deportes.json
  def index
    @deportes = Deporte.all
  end

  # GET /deportes/1 or /deportes/1.json
  def show
  end

  # GET /deportes/new
  def new
    @deporte = Deporte.new
  end

  # GET /deportes/1/edit
  def edit
  end

  # POST /deportes or /deportes.json
  def create
    @deporte = Deporte.new(deporte_params)

    respond_to do |format|
      if @deporte.save
        format.html { redirect_to deporte_url(@deporte), notice: "Deporte was successfully created." }
        format.json { render :show, status: :created, location: @deporte }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @deporte.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /deportes/1 or /deportes/1.json
  def update
    respond_to do |format|
      if @deporte.update(deporte_params)
        format.html { redirect_to deporte_url(@deporte), notice: "Deporte was successfully updated." }
        format.json { render :show, status: :ok, location: @deporte }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @deporte.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /deportes/1 or /deportes/1.json
  def destroy
    @deporte.destroy

    respond_to do |format|
      format.html { redirect_to deportes_url, notice: "Deporte was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_deporte
      @deporte = Deporte.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def deporte_params
      params.require(:deporte).permit(:encabezado, :cuepor, :link)
    end
end

app/helpers/deportes_helper.rb
module DeportesHelper
end

app/views/deportes/_deporte.html.erb
<div id="<%= dom_id deporte %>">
  <div class="card" style="width: 18rem;">
    <%= link_to (image_tag "01deportes.jpg", class: "card-img-top"), "/deportes/" %> 
    <div class="card-body">
      <h5 class="card-title"><%= deporte.encabezado %></h5>
      <p class="card-text"><%= deporte.cuepor %></p>
      <p class="card-text"> <strong>Link:</strong> <%= deporte.link %></p>
      <a href="#" class="btn btn-primary">Go somewhere</a>
    </div>
  </div>
</div>

app/views/deportes/_form.html.erb
<%= form_with(model: deporte) do |form| %>
  <% if deporte.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(deporte.errors.count, "error") %> prohibited this deporte from being saved:</h2>

      <ul>
        <% deporte.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :encabezado, style: "display: block" %>
    <%= form.text_field :encabezado %>
  </div>

  <div>
    <%= form.label :cuepor, style: "display: block" %>
    <%= form.text_area :cuepor %>
  </div>

  <div>
    <%= form.label :link, style: "display: block" %>
    <%= form.text_field :link %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/deportes/edit.html.erb
<h1>Editando Noticia de Deportes</h1>

<%= render "form", deporte: @deporte %>

<br>

<div>
  <%= link_to "Mostrar esta Noticia de Deportes", @deporte %> |
  <%= link_to "Volver a Noticias de Deportes", deportes_path %>
</div>

app/views/deportes/index.html.erb
<p style="color: green"><%= notice %></p>

<div  class="container" >
  <h1>Noticias de Deportes</h1>

  <div id="deportes">
    <div class="row">
      <% @deportes.each do |deporte| %>

        <div class="col">
            <%= render deporte %>
            <p><%= link_to "Mostrar esta Noticia de Deportes", deporte %></p>
        </div>
      <% end %>
    </div>
  </div>

  <%= link_to "Nueva Noticia de Deportes", new_deporte_path %>
</div>

app/views/deportes/new.html.erb
<h1>Nueva Noticia de Deportes</h1>

<%= render "form", deporte: @deporte %>

<br>

<div>
  <%= link_to "Volver a Noticias de Deportes", deportes_path %>
</div>

app/views/deportes/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @deporte %>

<div>
  <%= link_to "Editar esta Noticia de Deportes", edit_deporte_path(@deporte) %> |
  <%= link_to "Volver a Noticias de Deportes", deportes_path %>

  <%= button_to "Destruir esta Noticia de Deportes", @deporte, method: :delete %>
</div>