config/routes.rb
Rails.application.routes.draw do
  resources :politicas
  resources :internacionals
  resources :nacionals
  resources :farandulas
  resources :deportes
  resources :noticia
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "noticia#index"


end

app/models/internacional.rb
class Internacional < ApplicationRecord
end

app/controllers/internacionals_controller.rb
class InternacionalsController < ApplicationController
  before_action :set_internacional, only: %i[ show edit update destroy ]

  # GET /internacionals or /internacionals.json
  def index
    @internacionals = Internacional.all
  end

  # GET /internacionals/1 or /internacionals/1.json
  def show
  end

  # GET /internacionals/new
  def new
    @internacional = Internacional.new
  end

  # GET /internacionals/1/edit
  def edit
  end

  # POST /internacionals or /internacionals.json
  def create
    @internacional = Internacional.new(internacional_params)

    respond_to do |format|
      if @internacional.save
        format.html { redirect_to internacional_url(@internacional), notice: "Internacional was successfully created." }
        format.json { render :show, status: :created, location: @internacional }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @internacional.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /internacionals/1 or /internacionals/1.json
  def update
    respond_to do |format|
      if @internacional.update(internacional_params)
        format.html { redirect_to internacional_url(@internacional), notice: "Internacional was successfully updated." }
        format.json { render :show, status: :ok, location: @internacional }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @internacional.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /internacionals/1 or /internacionals/1.json
  def destroy
    @internacional.destroy

    respond_to do |format|
      format.html { redirect_to internacionals_url, notice: "Internacional was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_internacional
      @internacional = Internacional.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def internacional_params
      params.require(:internacional).permit(:encabezado, :cuepor, :link)
    end
end

app/helpers/internacionals_helper.rb
module InternacionalsHelper
end

app/views/internacionals/_form.html.erb
<%= form_with(model: internacional) do |form| %>
  <% if internacional.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(internacional.errors.count, "error") %> prohibited this internacional from being saved:</h2>

      <ul>
        <% internacional.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :encabezado, style: "display: block" %>
    <%= form.text_field :encabezado %>
  </div>

  <div>
    <%= form.label :cuepor, style: "display: block" %>
    <%= form.text_area :cuepor %>
  </div>

  <div>
    <%= form.label :link, style: "display: block" %>
    <%= form.text_field :link %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/internacionals/_internacional.html.erb
<div id="<%= dom_id internacional %>">
  <div class="card" style="width: 18rem;">
    <%= link_to (image_tag "04internacional.jpg", class: "card-img-top"), "/interacionals/" %> 
    <div class="card-body">
      <h5 class="card-title"><%= internacional.encabezado %></h5>
      <p class="card-text"><%= internacional.cuepor %></p>
      <p class="card-text"> <strong>Link:</strong> <%= internacional.link %></p>
      <a href="#" class="btn btn-primary">Go somewhere</a>
    </div>
  </div>
</div>

app/views/internacionals/edit.html.erb
<h1>Editando Noticia Internacional</h1>

<%= render "form", internacional: @internacional %>

<br>

<div>
  <%= link_to "Mostrar esta Noticia Internacional", @internacional %> |
  <%= link_to "Volver a Noticias Internacionales", internacionals_path %>
</div>

app/views/internacionals/index.html.erb
<p style="color: green"><%= notice %></p>

<div  class="container" >
  <h1>Noticias Internacionales</h1>

  <div id="internacionals">
    <div class="row">
      <% @internacionals.each do |internacional| %>

        <div class="col">
            <%= render internacional %>
            <p><%= link_to "Mostrar esta Noticia Internacional", internacional %></p>
        </div>
      <% end %>
    </div>
  </div>

  <%= link_to "Nueva Noticia Internacional", new_internacional_path %>
</div>

app/views/internacionals/new.html.erb
<h1>Nueva Noticia Internacional</h1>

<%= render "form", internacional: @internacional %>

<br>

<div>
  <%= link_to "Volver a Noticias Internacionales", internacionals_path %>
</div>

app/views/internacionals/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @internacional %>

<div>
  <%= link_to "Editar esta Noticia Internacional", edit_internacional_path(@internacional) %> |
  <%= link_to "Volver a Noticias Internacionales", internacionals_path %>

  <%= button_to "Destruir esta Noticia Internacional", @internacional, method: :delete %>
</div>