config/routes.rb
Rails.application.routes.draw do
  resources :politicas
  resources :internacionals
  resources :nacionals
  resources :farandulas
  resources :deportes
  resources :noticia
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "noticia#index"


end

app/models/farandula.rb
class Farandula < ApplicationRecord
end

app/controllers/farandulas_controller.rb
class FarandulasController < ApplicationController
  before_action :set_farandula, only: %i[ show edit update destroy ]

  # GET /farandulas or /farandulas.json
  def index
    @farandulas = Farandula.all
  end

  # GET /farandulas/1 or /farandulas/1.json
  def show
  end

  # GET /farandulas/new
  def new
    @farandula = Farandula.new
  end

  # GET /farandulas/1/edit
  def edit
  end

  # POST /farandulas or /farandulas.json
  def create
    @farandula = Farandula.new(farandula_params)

    respond_to do |format|
      if @farandula.save
        format.html { redirect_to farandula_url(@farandula), notice: "Farandula was successfully created." }
        format.json { render :show, status: :created, location: @farandula }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @farandula.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /farandulas/1 or /farandulas/1.json
  def update
    respond_to do |format|
      if @farandula.update(farandula_params)
        format.html { redirect_to farandula_url(@farandula), notice: "Farandula was successfully updated." }
        format.json { render :show, status: :ok, location: @farandula }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @farandula.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /farandulas/1 or /farandulas/1.json
  def destroy
    @farandula.destroy

    respond_to do |format|
      format.html { redirect_to farandulas_url, notice: "Farandula was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_farandula
      @farandula = Farandula.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def farandula_params
      params.require(:farandula).permit(:encabezado, :cuepor, :link)
    end
end

app/helpers/farandulas_helper.rb
module FarandulasHelper
end

app/views/farandulas/_farandula.html.erb
<div id="<%= dom_id farandula %>">
  <div class="card" style="width: 18rem;">
    <%= link_to (image_tag "02farandula.jpg", class: "card-img-top"), "/farandulas/" %> 
    <div class="card-body">
      <h5 class="card-title"><%= farandula.encabezado %></h5>
      <p class="card-text"><%= farandula.cuepor %></p>
      <p class="card-text"> <strong>Link:</strong> <%= farandula.link %></p>
      <a href="#" class="btn btn-primary">Go somewhere</a>
    </div>
  </div>
</div>

app/views/farandulas/_form.html.erb
<%= form_with(model: farandula) do |form| %>
  <% if farandula.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(farandula.errors.count, "error") %> prohibited this farandula from being saved:</h2>

      <ul>
        <% farandula.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :encabezado, style: "display: block" %>
    <%= form.text_field :encabezado %>
  </div>

  <div>
    <%= form.label :cuepor, style: "display: block" %>
    <%= form.text_area :cuepor %>
  </div>

  <div>
    <%= form.label :link, style: "display: block" %>
    <%= form.text_field :link %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/farandulas/edit.html.erb
<h1>Editiando Noticia de Farándula</h1>

<%= render "form", farandula: @farandula %>

<br>

<div>
  <%= link_to "Mostrar esta Noticia de Farándula", @farandula %> |
  <%= link_to "Volver a Noticias de Farándula", farandulas_path %>
</div>

app/views/farandulas/index.html.erb
<p style="color: green"><%= notice %></p>

<div  class="container" >
  <h1>Noticias de Farándula</h1>

  <div id="farandulas">
    <div class="row">
      <% @farandulas.each do |farandula| %>

        <div class="col">
            <%= render farandula %>
            <p><%= link_to "Mostrar esta Noticia de Farándula", farandula %></p>
        </div>
      <% end %>
    </div>
  </div>

  <%= link_to "Nueva Noticia de Farándula", new_farandula_path %>
</div>

app/views/farandulas/new.html.erb
<h1>Nueva Noticia de Farándula</h1>

<%= render "form", farandula: @farandula %>

<br>

<div>
  <%= link_to "Volver a Noticias de Farándula", farandulas_path %>
</div>

app/views/farandulas/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @farandula %>

<div>
  <%= link_to "Editar esta Noticia de Farándula", edit_farandula_path(@farandula) %> |
  <%= link_to "Volver a Noticias de Farándula", farandulas_path %>

  <%= button_to "Destruir esta Noticia de Farándula", @farandula, method: :delete %>
</div>