config/routes.rb
Rails.application.routes.draw do
  resources :politicas
  resources :internacionals
  resources :nacionals
  resources :farandulas
  resources :deportes
  resources :noticia
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "noticia#index"


end

app/models/nacional.rb
class Nacional < ApplicationRecord
end

app/controllers/nacionals_controller.rb
class NacionalsController < ApplicationController
  before_action :set_nacional, only: %i[ show edit update destroy ]

  # GET /nacionals or /nacionals.json
  def index
    @nacionals = Nacional.all
  end

  # GET /nacionals/1 or /nacionals/1.json
  def show
  end

  # GET /nacionals/new
  def new
    @nacional = Nacional.new
  end

  # GET /nacionals/1/edit
  def edit
  end

  # POST /nacionals or /nacionals.json
  def create
    @nacional = Nacional.new(nacional_params)

    respond_to do |format|
      if @nacional.save
        format.html { redirect_to nacional_url(@nacional), notice: "Nacional was successfully created." }
        format.json { render :show, status: :created, location: @nacional }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @nacional.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /nacionals/1 or /nacionals/1.json
  def update
    respond_to do |format|
      if @nacional.update(nacional_params)
        format.html { redirect_to nacional_url(@nacional), notice: "Nacional was successfully updated." }
        format.json { render :show, status: :ok, location: @nacional }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @nacional.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /nacionals/1 or /nacionals/1.json
  def destroy
    @nacional.destroy

    respond_to do |format|
      format.html { redirect_to nacionals_url, notice: "Nacional was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_nacional
      @nacional = Nacional.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def nacional_params
      params.require(:nacional).permit(:encabezado, :cuepor, :link)
    end
end

app/helpers/nacionals_helper.rb
module NacionalsHelper
end

app/views/nacionals/_form.html.erb
<%= form_with(model: nacional) do |form| %>
  <% if nacional.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(nacional.errors.count, "error") %> prohibited this nacional from being saved:</h2>

      <ul>
        <% nacional.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :encabezado, style: "display: block" %>
    <%= form.text_field :encabezado %>
  </div>

  <div>
    <%= form.label :cuepor, style: "display: block" %>
    <%= form.text_area :cuepor %>
  </div>

  <div>
    <%= form.label :link, style: "display: block" %>
    <%= form.text_field :link %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/nacionals/_nacional.html.erb
<div id="<%= dom_id nacional %>">
  <div class="card" style="width: 18rem;">
    <%= link_to (image_tag "03nacional.jpg", class: "card-img-top"), "nacionals/" %> 
    <div class="card-body">
      <h5 class="card-title"><%= nacional.encabezado %></h5>
      <p class="card-text"><%= nacional.cuepor %></p>
      <p class="card-text"> <strong>Link:</strong> <%= nacional.link %></p>
      <a href="#" class="btn btn-primary">Go somewhere</a>
    </div>
  </div>
</div>

app/views/nacionals/edit.html.erb
<h1>Editando Noticia Nacional</h1>

<%= render "form", nacional: @nacional %>

<br>

<div>
  <%= link_to "Mostrar esta Noticia Nacional", @nacional %> |
  <%= link_to "Volver a Noticias Nacionales", nacionals_path %>
</div>

app/views/nacionals/index.html.erb
<p style="color: green"><%= notice %></p>

<div  class="container" >
  <h1>Noticias Nacionales</h1>

  <div id="nacionals">
    <div class="row">
      <% @nacionals.each do |nacional| %>

        <div class="col">
            <%= render nacional %>
            <p><%= link_to "Mostrar esta Noticia Nacional", nacional %></p>
        </div>
      <% end %>
    </div>
  </div>

  <%= link_to "Nueva Noticia Nacional", new_nacional_path %>
</div>

app/views/nacionals/new.html.erb
<h1>Nueva Noticia Nacional</h1>

<%= render "form", nacional: @nacional %>

<br>

<div>
  <%= link_to "Volver a Noticias Nacionales", nacionals_path %>
</div>

app/views/nacionals/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @nacional %>

<div>
  <%= link_to "Editar esta Noticia Nacional", edit_nacional_path(@nacional) %> |
  <%= link_to "Volver a Noticias Nacionales", nacionals_path %>

  <%= button_to "Destruir a Noticias Nacionales", @nacional, method: :delete %>
</div>